server:
  port: 8099
  servlet:
    context-path: /qualificacao

spring:
  application:
    name: qualificacao

  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_URL:mongodb://root:example@localhost:27017/qualificacao?authSource=admin}

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}

  cloud:
    function:
      definition: pedidoCriado
    stream:
      bindings:
        pedidoCriado-in-0:
          destination: pedido-criado
          group: qualificacao-ms

        pedidoQualificado-out-0:
          destination: pedido-qualificado

        pedidoRecusado-out-0:
          destination: pedido-recusado

      rabbit:
        bindings:
          # CONSUMER
          pedidoCriado-in-0:
            consumer:
              exchangeType: fanout
              autoBindDlq: true
              deadLetterExchange: qualificacao-processing-error
              deadLetterExchangeType: fanout
              dlqMaxLength: 100
              dlqTtl: 120000

          # PRODUCER
          pedidoQualificado-out-0:
            producer:
              exchangeType: fanout

          pedidoRecusado-out-0:
            producer:
              exchangeType: fanout

      binders:
        rabbitmq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${RABBIT_HOST:localhost}
                port: ${RABBIT_PORT:5672}
                username: ${RABBIT_USERNAME:guest}
                password: ${RABBIT_PASSWORD:guest}
                virtual-host: /

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
