

spring:
  application:
    name: auth
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  jmx:
    enable: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/auth
    username: postgres
    password: 123456

security:
  jwt:
    token:
      security-key: VGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBmb3IgdGVzdA==
      expire-length: 360000

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8088
  servlet:
    context-path: /auth