spring:
  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_URL:mongodb://root:example@localhost:27017/projeto1?authSource=admin}

  cloud:
    function:
      definition: pedidoEmbalado;pedidoEnvioConfirmado;
    stream:
      bindings:
        pedidoEmbalado-in-0:
          destination: pedido-embalado
          group: envio
        pedidoEnvioConfirmado-in-0:
          destination: pedido-envio-confirmado
          group: envio

        pedidoEnvioSolicitado-out-0:
            destination: pedido-envio-solicitado
        pedidoEnviado-out-0:
            destination: pedido-enviado
      rabbit:
        bindings:
            # CONSUMER
          pedidoEmbalado-in-0:
              consumer:
                exchangeType: fanout
                autoBindDlq: true
                deadLetterExchange: envio-processing-error
                deadLetterExchangeType: fanout
                dlqMaxLength: 100
                dlqTtl: 120000
          pedidoEnvioConfirmado-in-0:
              consumer:
                exchangeType: fanout
                autoBindDlq: true
                deadLetterExchange: envio-processing-error
                deadLetterExchangeType: fanout
                dlqMaxLength: 100
                dlqTtl: 120000

              # PRODUCER
          pedidoEnvioSolicitado-out-0:
            producer:
              exchangeType: fanout
          pedidoEnviado-out-0:
            producer:
              exchangeType: fanout
            binders:
              rabbitmq:
                type: rabbit
                environment:
                spring:
                    host: ${RABBIT_HOST:localhost}
                    port: ${RABBIT_PORT:5672}
                    username: ${RABBIT_USERNAME:guest}
                    password: ${RABBIT_PASSWORD:guest}
                    virtual-host: /
  application:
    name: envio
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}

server:
  port: 9999


  servlet:
    context-path: /envio
