server:
  port: 8081

spring:
  application:
    name: gateway

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka/

zuul:
  prefix: /api
  ignored-services: "*"

  routes:
    produtos:
      path: /produtos/**
      service-id: produtos
      strip-prefix: false
      custom-sensitive-headers: true

    pagamento:
        path: /pagamento/**
        service-id: pagamento
        strip-prefix: false
        custom-sensitive-headers: true

    auth:
      path: /auth/**
      service-id: auth
      strip-prefix: false
      custom-sensitive-headers: true