server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: produtos
          uri: lb://produtos
          predicates:
            - Path=/produtos/**
        - id: pagamento
          uri: lb://pagamento
          predicates:
            - Path=/pagamento/**
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
        - id: pedido
          uri: lb://pedido/**
          predicates:
            - Path=/pedido/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/