server:
  port: 8081

spring:
  application:
    name: gateway
  security:
    oauth2:
     resourceserver:
       jwt:
         secret: eHk10qTbSU9zJY7lCi+sIOL5BJVwN/JRSQByqvgb2ibOVwSINnCBiKXMYx/Zj2xhsbm+QULnUUtvATDjzC1Oag==
         validity: 3600000

  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
        - id: produtos
          uri: lb://produtos
          predicates:
            - Path=/produtos/**
        - id: pagamento
          uri: lb://pagamento
          predicates:
            - Path=/pagamento/**
        - id: pedido
          uri: lb://pedido
          predicates:
            - Path=/pedido/**
        - id: qualificacao
          uri: lb://qualificacao
          predicates:
            - Path=/qualificacao/**
        - id: fulfillments
          uri: lb://fulfillments
          predicates:
            - Path=/fulfillments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
