server:
  port: 8089
  servlet:
    context-path: /pagamento

spring:
  application:
    name: pagamento
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  jmx:
    enable: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/pagamento
    username: postgres
    password: 123456

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


pagamento:
  rabbitmq:
    exchange: pedido.exchange
    queue: pedido.queue

security:
  jwt:
    token:
      security-key: VGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBmb3IgdGVzdA==

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
