server:
  port: 8080
  servlet:
    context-path: /produtos

spring:
  application:
    name: produtos
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  jmx:
    enable: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/produtos
    username: postgres
    password: 123456

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

produtos:
  rabbitmq:
    exchange: produtos.exchange
    routingkey: produtos.routingkey

security:
  jwt:
    token:
      security-key: chave_microservico

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka/
